name: Linter

on:
  push:
    branches:
      - "*"
      - "!master"
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install yarn lastest version
        run: |
          corepack enable
          yarn set version berry

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.15.0'

      - name: Install dependencies
        run: yarn --immutable

      - name: Run Linter
        run: yarn lint
        env:
          CI: true