name: Check and Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: ["master"]

jobs:
  # pr_check:
  #   name: PR Check
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [18.x]

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: PR Check with Node ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}


  #     - name: PR Check
  #       run: |
  #         yarn --frozen-lockfile
  #         yarn lint
  #         yarn type-check

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unit Tests with Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run Cypress on Node ${{ matrix.node-version }}
        run: yarn cy:run
